spring.application.name=rental-room
server.port = 9998

# C?u hình DataSource cho PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/rental_room
spring.datasource.username=admin
spring.datasource.password=macbook_pro16

# C?u hình JPA và Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public

# Hi?n th? câu l?nh SQL trong log (tùy ch?n, h?u ích cho debug)
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true