spring.application.name=rental-room
server.port = 9998

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/rental_room_db
spring.datasource.username=admin
spring.datasource.password=0DF5A6FB8628
#spring.jpa.hibernate.ddl-auto=update